# Generated by Django 5.0.6 on 2024-06-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_campaign_rename_created_at_address_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='campaign',
        ),
    ]
