# Generated by Django 5.0.6 on 2024-06-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
