# Generated by Django 5.0.6 on 2024-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_orderitem_cancellation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='campaign',
        ),
    ]
