# Generated by Django 5.0.6 on 2024-06-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_campaign_alter_address_last_update_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='campaign',
        ),
    ]
