# Generated by Django 5.0.6 on 2024-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_order_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
