# Generated by Django 5.0.6 on 2024-06-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_campaign_campaign_name_alter_campaign_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
