# Generated by Django 5.0.6 on 2024-06-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_delete_campaign_alter_address_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cancellation_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
