# Generated by Django 5.0.6 on 2024-06-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_campaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
