# Generated by Django 5.0.6 on 2024-06-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=255)),
                ('authorization_code', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('payment_gateway_response', models.TextField()),
                ('payment_notes', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.order')),
            ],
        ),
    ]
